class_name BattleEventTypes
extends RefCounted

const ACTION_BLOCKED := "action_blocked"
const ATTACK_MISSED := "attack_missed"
const BATTLE_FINISHED := "battle_finished"
const BATTLE_STARTED := "battle_started"
const COOLDOWN_READY := "cooldown_ready"
const COOLDOWN_STARTED := "cooldown_started"
const DAMAGE_APPLIED := "damage_applied"
const DRILL_COMPLETED := "drill_completed"
const DRILL_STARTED := "drill_started"
const FARMING_TRIGGERED := "farming_triggered"
const HEALING_APPLIED := "healing_applied"
const MANA_CHANGED := "mana_changed"
const MARK_APPLIED := "mark_applied"
const MARK_EXPIRED := "mark_expired"
const MARK_TRIGGERED := "mark_triggered"
const NEUTRAL_OBJECTIVE_SLAIN := "neutral_objective_slain"
const NEUTRAL_OBJECTIVE_SPAWNED := "neutral_objective_spawned"
const OBJECTIVE_DESTROYED := "objective_destroyed"
const PLAYER_SWITCHED := "player_switched"
const REINFORCEMENT_STARTED := "reinforcement_started"
const REWARD_GRANTED := "reward_granted"
const SKILL_LEVELED_UP := "skill_leveled_up"
const SKILL_STARTED := "skill_started"
const SKILL_XP_GAINED := "skill_xp_gained"
const STATUS_APPLIED := "status_applied"
const STATUS_EXPIRED := "status_expired"
